import React, { createContext, useState, useContext } from 'react';

const translations = {
  en: {
    exchange: 'Exchange',
    proforma: 'Proforma',
    opportunities: 'Opportunities',
    account: 'Account',
    proceed: 'Proceed',
    bankRate: 'Bank Rate (Official)',
    blackMarketRate: 'Black Market Rate',
    shapShapFees: 'ShapShap Fees',
    ourFee: 'Our Fee',
    networkFee: 'Network Fee',
    totalPay: 'Total Pay',
    youGet: 'You get',
    youSave: 'You Save',
    rateLock: 'Rate Lock',
    locked: 'Locked',
    lockRate: 'Lock Rate',
    goPremium: 'Go Premium',
    standard: 'Standard',
    getRenminbi: 'Get RENMINBI',
    transfer: 'Transfer',
    myAccount: 'My Account',
    bankTransfer: 'Bank Transfer',
    mobileMoney: 'Mobile Money',
    debitCard: 'Debit Card',
    accountNumber: 'Account Number',
    ok: 'OK',
    sendRenminbi: 'Send RENMINBI',
    amountRmb: 'Amount in RMB',
    sendToAccount: 'Send to Account Number',
    pay: 'Pay',
    insufficient: 'Insufficient balance.',
    success: 'Success! Your payment is being processed.',
    checkAccount: 'Please check "My Account" to view your Renminbi card balance.',
    fastReliable: 'Fast and Reliable!',
    anxietyReduce: 'ShapShap is designed to reduce the anxiety of cross-border trade.',
    premiumLock: 'Premium Lock (60s)',
    standardLock: 'Standard Lock (15s)',
    guaranteed: 'active. Guaranteed rate for this transaction.',
    amountIn: 'Amount in',
    liveAiCalculator: 'Live AI Rate Calculator',
    selectCountry: 'Select Country',
    selectPayment: 'Select Payment Method',
    enterValid: 'Please enter a valid recipient account and amount.',
    enterAmountToConvert: 'Please enter the amount you wish to convert to receive in your Alipay or WeChat Pay.',
    processedSuccess: 'processed successfully!',
    productCostCalc: 'Product Cost Calculation',
    unitPrice: 'Unit Price',
    quantity: 'Quantity',
    calculateCost: 'Calculate Cost',
    total: 'Total',
    downloadPdf: 'Download PDF',
    documentPreview: 'Document Preview',
    invoiceReady: 'Invoice Ready',
    reference: 'Reference',
    generateToPreview: 'Generate cost to preview',
    comingSoon: 'Service coming soon!',
    exclusiveMembers: 'Exclusive to members',
    unlockOpportunity: 'Unlock Opportunity',
    marketOpportunities: 'Market Opportunities',
    curatedInsights: 'Curated high-value insights and supply chain gaps ready for disruption.',
    selectSupplierPrompt: 'Please select a supplier from the Opportunities or Suppliers section.',
    serviceShipping: 'Shipping & International Freight',
    serviceInsurance: 'Insurance for the shipment',
    serviceDuties: 'Import Duties & Taxes',
    serviceLogistics: 'Local Logistics',
    serviceCustoms: 'Customs Brokerage Fees',
    deposit: 'Deposit',
    depositAmount: 'Deposit Amount',
    mobileMoneyNumber: 'Mobile Money Number',
    enterReference: 'Enter transaction reference',
    bankDetails: 'Bank Details',
    accountHolderName: 'Account Holder\'s Name',
    alipay: 'AliPay',
    wechatpay: 'WeChatPay',
    profile: 'Profile',
    history: 'History',
    security: 'Security',
    startDate: 'Start Date',
    endDate: 'End Date',
    status: 'Status',
    successTransferMsg: 'Please check transfer process in the Account Tab.',
    bankTransferInstruction: 'Please transfer to the following bank account:',
    bankAccountDetails: 'Bank Name: ShapShap Bank\nAccount No: 1234567890',
    transactionRef: 'Transaction Reference',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    changePassword: 'Change Password',
    enable2FA: 'Enable 2FA',
    transactions: 'Transactions',
    downloadPdf: 'Download PDF',
    completed: 'Completed',
    pending: 'Pending',
    failed: 'Failed',
    check: 'Check'
  },
  fr: {
    exchange: 'Échange',
    proforma: 'Proforma',
    opportunities: 'Opportunités',
    account: 'Compte',
    proceed: 'Continuer',
    bankRate: 'Taux Bancaire (Officiel)',
    blackMarketRate: 'Taux du Marché Noir',
    shapShapFees: 'Frais ShapShap',
    ourFee: 'Nos Frais',
    networkFee: 'Frais de Réseau',
    totalPay: 'Total à Payer',
    youGet: 'Vous recevez',
    youSave: 'Vous économisez',
    rateLock: 'Bloquer le Taux',
    locked: 'Bloqué',
    lockRate: 'Bloquer',
    goPremium: 'Passer en Premium',
    standard: 'Standard',
    getRenminbi: 'Obtenir des RENMINBI',
    transfer: 'Transfert',
    myAccount: 'Mon Compte',
    bankTransfer: 'Virement Bancaire',
    mobileMoney: 'Mobile Money',
    debitCard: 'Carte Bancaire',
    accountNumber: 'Numéro de Compte',
    ok: 'Valider',
    sendRenminbi: 'Envoyer des RENMINBI',
    amountRmb: 'Montant en RMB',
    sendToAccount: 'Envoyer au Numéro de Compte',
    pay: 'Payer',
    insufficient: 'Solde insuffisant.',
    success: 'Succès ! Votre paiement est en cours de traitement.',
    checkAccount: 'Veuillez vérifier "Mon Compte" pour voir votre solde en Renminbi.',
    fastReliable: 'Rapide et Fiable !',
    anxietyReduce: 'ShapShap est conçu pour réduire l\'anxiété du commerce transfrontalier.',
    premiumLock: 'Blocage Premium (60s)',
    standardLock: 'Blocage Standard (15s)',
    guaranteed: 'activé. Taux garanti pour cette transaction.',
    amountIn: 'Montant en',
    liveAiCalculator: 'Calculateur de Taux IA en Direct',
    selectCountry: 'Choisir le Pays',
    selectPayment: 'Choisir le Mode de Paiement',
    enterValid: 'Veuillez saisir un compte destinataire et un montant valides.',
    enterAmountToConvert: 'Veuillez saisir le montant que vous souhaitez convertir pour recevoir sur votre Alipay ou WeChat Pay.',
    processedSuccess: 'traité avec succès !',
    productCostCalc: 'Calcul du Coût du Produit',
    unitPrice: 'Prix Unitaire',
    quantity: 'Quantité',
    calculateCost: 'Calculer le Coût',
    total: 'Total',
    downloadPdf: 'Télécharger le PDF',
    documentPreview: 'Aperçu du Document',
    invoiceReady: 'Facture Prête',
    reference: 'Référence',
    generateToPreview: 'Générer le coût pour l\'aperçu',
    comingSoon: 'Service bientôt disponible !',
    exclusiveMembers: 'Exclusif aux membres',
    unlockOpportunity: 'Débloquer l\'Opportunité',
    marketOpportunities: 'Opportunités du Marché',
    curatedInsights: 'Aperçus de haute valeur et lacunes de la chaîne d\'approvisionnement prêts pour la disruption.',
    selectSupplierPrompt: 'Veuillez sélectionner un fournisseur dans la section Opportunités ou Fournisseurs.',
    serviceShipping: 'Expédition et Fret International',
    serviceInsurance: 'Assurance pour l\'expédition',
    serviceDuties: 'Droits de Douane et Taxes',
    serviceLogistics: 'Logistique Locale',
    serviceCustoms: 'Frais de Courtage en Douane',
    deposit: 'Dépôt',
    depositAmount: 'Montant du Dépôt',
    mobileMoneyNumber: 'Numéro Mobile Money',
    enterReference: 'Entrez la référence de la transaction',
    bankDetails: 'Coordonnées Bancaires',
    accountHolderName: 'Nom du Titulaire du Compte',
    alipay: 'AliPay',
    wechatpay: 'WeChatPay',
    profile: 'Profil',
    history: 'Historique',
    security: 'Sécurité',
    startDate: 'Date de Début',
    endDate: 'Date de Fin',
    status: 'Statut',
    successTransferMsg: 'Veuillez vérifier le processus de transfert dans l\'onglet Compte.',
    bankTransferInstruction: 'Veuillez effectuer le virement vers le compte bancaire suivant :',
    bankAccountDetails: 'Nom de la Banque : ShapShap Bank\nN° de Compte : 1234567890',
    transactionRef: 'Référence de Transaction',
    email: 'E-mail',
    phone: 'Téléphone',
    address: 'Adresse',
    changePassword: 'Changer le Mot de Passe',
    enable2FA: 'Activer 2FA',
    transactions: 'Transactions',
    downloadPdf: 'Télécharger le PDF',
    completed: 'Terminé',
    pending: 'En Attente',
    failed: 'Échoué',
    check: 'Vérifier'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language][key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'fr' : 'en');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);